#!/usr/bin/env bash
# Create the riot-proxy dev VM on a Proxmox VE host (OPS-02, ADR-070).
# Run as root on the host, from an unpacked copy of this repo. See README.md here.
#
# The VM is Debian 13 (cloud image) with Docker. Proxmox's own cloud-init sets
# the user, SSH keys and network; a vendor-data snippet installs Docker, the
# compose stack in /opt/riot-proxy and a timer that pulls :edge every 2 minutes.
set -euo pipefail

here=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

IMAGE_URL=https://cloud.debian.org/images/cloud/trixie/latest/debian-13-genericcloud-amd64.qcow2
SUMS_URL=https://cloud.debian.org/images/cloud/trixie/latest/SHA512SUMS

vmid=""
name=riot-proxy-dev
storage=local-lvm
snippets=local
bridge=vmbr0
cores=2
memory=2048
disk=16G
ip=dhcp
gw=""
ciuser=riot
ssh_keys=""
gen_key=0
key_dir=/root/.ssh/riot-proxy
image_dir=/var/tmp/riot-proxy-images
start=1
mode=run

usage() {
  cat <<EOF
usage: $0 --ssh-keys FILE | --generate-key [options]

  --ssh-keys FILE      public keys for the VM user
  --generate-key       make a new ed25519 keypair for this VM in --key-dir
                       (with --ssh-keys, the VM accepts both)
  --key-dir DIR        where --generate-key writes <name>-<vmid>[.pub] (default: $key_dir)
  --vmid N             VM id (default: the cluster's next free id)
  --name NAME          VM name (default: $name)
  --storage ID         disk + cloud-init drive storage (default: $storage)
  --snippets ID        storage with the 'snippets' content type (default: $snippets)
  --bridge BRIDGE      network bridge (default: $bridge)
  --cores N            (default: $cores)
  --memory MB          (default: $memory)
  --disk SIZE          root disk size (default: $disk)
  --ip CIDR|dhcp       static address like 192.168.68.50/22, or dhcp (default)
  --gw ADDR            gateway, with a static --ip
  --user NAME          VM login user (default: $ciuser)
  --no-start           create the VM but do not start it
  --dry-run            print the qm/pvesm commands instead of running them
  --print-vendor-data  print the cloud-init vendor-data and exit
EOF
}

die() { echo "create-vm: $*" >&2; exit 1; }

while [ $# -gt 0 ]; do
  case "$1" in
    --ssh-keys) ssh_keys=$2; shift ;;
    --generate-key) gen_key=1 ;;
    --key-dir) key_dir=$2; shift ;;
    --vmid) vmid=$2; shift ;;
    --name) name=$2; shift ;;
    --storage) storage=$2; shift ;;
    --snippets) snippets=$2; shift ;;
    --bridge) bridge=$2; shift ;;
    --cores) cores=$2; shift ;;
    --memory) memory=$2; shift ;;
    --disk) disk=$2; shift ;;
    --ip) ip=$2; shift ;;
    --gw) gw=$2; shift ;;
    --user) ciuser=$2; shift ;;
    --no-start) start=0 ;;
    --dry-run) mode=dry ;;
    --print-vendor-data) mode=vendor ;;
    -h|--help) usage; exit 0 ;;
    *) usage >&2; die "unknown option: $1" ;;
  esac
  shift
done

[[ $ciuser =~ ^[a-z_][a-z0-9_-]*$ ]] || die "--user must be a plain login name"
[[ $name =~ ^[A-Za-z0-9][A-Za-z0-9.-]*$ ]] || die "--name must be a DNS name"

b64() { base64 -w0 < "$here/files/$1"; }

# Cloud-init vendor-data. Files go in as base64 so their contents can't break the YAML.
vendor_data() {
  cat <<EOF
#cloud-config
# Generated by deploy/proxmox/create-vm.sh (OPS-02).
package_update: true
package_upgrade: true
packages: [qemu-guest-agent, docker.io, docker-compose, unattended-upgrades]
write_files:
  - path: /opt/riot-proxy/compose.yaml
    encoding: b64
    content: $(b64 compose.yaml)
  - path: /opt/riot-proxy/env.example
    encoding: b64
    content: $(b64 env.example)
  - path: /usr/local/bin/riot-proxy-update
    permissions: "0755"
    encoding: b64
    content: $(b64 riot-proxy-update)
  - path: /etc/systemd/system/riot-proxy-update.service
    encoding: b64
    content: $(b64 riot-proxy-update.service)
  - path: /etc/systemd/system/riot-proxy-update.timer
    encoding: b64
    content: $(b64 riot-proxy-update.timer)
runcmd:
  - [sh, -c, "test -f /opt/riot-proxy/.env || install -m 600 /opt/riot-proxy/env.example /opt/riot-proxy/.env"]
  - [mkdir, -p, /opt/riot-proxy/data]
  - [chown, -R, "$ciuser:$ciuser", /opt/riot-proxy]
  - [usermod, -aG, docker, "$ciuser"]
  - [systemctl, daemon-reload]
  - [systemctl, enable, --now, qemu-guest-agent, docker, riot-proxy-update.timer]
EOF
}

if [ "$mode" = vendor ]; then
  vendor_data
  exit 0
fi

[ -n "$ssh_keys" ] || [ "$gen_key" = 1 ] || { usage >&2; die "--ssh-keys or --generate-key is required"; }
[ -z "$ssh_keys" ] || [ -r "$ssh_keys" ] || die "can't read $ssh_keys"
if [ "$ip" = dhcp ]; then
  ipconfig="ip=dhcp"
else
  [ -n "$gw" ] || die "a static --ip needs --gw"
  ipconfig="ip=$ip,gw=$gw"
fi

run() {
  if [ "$mode" = dry ]; then printf '%q ' "$@"; echo; else "$@"; fi
}

if [ "$mode" = run ]; then
  [ "$(id -u)" = 0 ] || die "run as root on the Proxmox host"
  command -v qm >/dev/null || die "qm not found; this must run on a Proxmox VE host"
  pvesm status --content snippets 2>/dev/null | awk 'NR>1{print $1}' | grep -qx "$snippets" \
    || die "storage '$snippets' has no 'snippets' content type; add it (Datacenter → Storage → $snippets → Content) or pass --snippets"
  [ "$gen_key" = 0 ] || command -v ssh-keygen >/dev/null || die "ssh-keygen not found; install openssh-client"
fi

[ -n "$vmid" ] || vmid=$(if [ "$mode" = dry ]; then echo 9000; else pvesh get /cluster/nextid; fi)
[[ $vmid =~ ^[0-9]+$ ]] || die "--vmid must be a number"
snippet="riot-proxy-dev-$vmid.yaml"
image="$image_dir/$(basename "$IMAGE_URL")"

# A fresh keypair per VM, named after it, so no two VMs share a login key.
keys_file=$ssh_keys
if [ "$gen_key" = 1 ]; then
  key="$key_dir/$name-$vmid"
  [ "$mode" = dry ] || [ ! -e "$key" ] || die "$key already exists; delete it (and $key.pub) or pass --key-dir"
  run install -d -m 700 "$key_dir"
  run ssh-keygen -q -t ed25519 -N '' -C "$ciuser@$name-$vmid" -f "$key"
  if [ -n "$ssh_keys" ]; then
    keys_file=$(mktemp)
    trap 'rm -f "$keys_file"' EXIT
    if [ "$mode" = run ]; then cat "$ssh_keys" "$key.pub" > "$keys_file"; fi
  else
    keys_file="$key.pub"
  fi
fi

# Download (or refresh) the Debian cloud image and check it against Debian's SHA512SUMS.
run mkdir -p "$image_dir"
if [ -f "$image" ]; then
  run curl -fsSL -z "$image" -o "$image" "$IMAGE_URL"
else
  run curl -fsSL -o "$image" "$IMAGE_URL"
fi
if [ "$mode" = run ]; then
  sum=$(curl -fsSL "$SUMS_URL" | awk -v f="$(basename "$IMAGE_URL")" '$2==f{print $1}')
  [ -n "$sum" ] || die "no checksum for $(basename "$IMAGE_URL") in $SUMS_URL"
  echo "$sum  $image" | sha512sum -c --quiet - || die "checksum mismatch for $image; delete it and retry"
  snippet_path=$(pvesm path "$snippets:snippets/$snippet")
  vendor_data > "$snippet_path"
  echo "create-vm: wrote $snippet_path"
else
  echo "# vendor-data → $snippets:snippets/$snippet (see --print-vendor-data)"
fi

run qm create "$vmid" --name "$name" --ostype l26 --cpu host --cores "$cores" --memory "$memory" \
  --net0 "virtio,bridge=$bridge" --scsihw virtio-scsi-single --agent enabled=1 \
  --serial0 socket --vga serial0
run qm set "$vmid" --scsi0 "$storage:0,import-from=$image,discard=on,ssd=1"
run qm resize "$vmid" scsi0 "$disk"
run qm set "$vmid" --ide2 "$storage:cloudinit" --boot order=scsi0
run qm set "$vmid" --ciuser "$ciuser" --sshkeys "$keys_file" --ipconfig0 "$ipconfig" \
  --cicustom "vendor=$snippets:snippets/$snippet"
state="created (not started)"
if [ "$start" = 1 ]; then
  run qm start "$vmid"
  state="created and booting"
fi

login="ssh $ciuser@<vm>"
if [ "$gen_key" = 1 ]; then
  login="ssh -i ~/.ssh/$name-$vmid $ciuser@<vm>"
  cat <<EOF
create-vm: login key for VM $vmid: $key (public: $key.pub)
  Copy it to your machine:  scp root@$(hostname):$key ~/.ssh/$name-$vmid
  then delete it here if you like: rm $key
EOF
fi

cat <<EOF
create-vm: VM $vmid ($name) $state.
Next:
  1. Find its address:   qm guest cmd $vmid network-get-interfaces   (once the agent is up, ~1-2 min)
  2. Set RIOT_API_KEY:   $login, then edit /opt/riot-proxy/.env
  3. Start it now:       sudo riot-proxy-update   (or wait; the timer runs every 2 minutes)
  4. Open http://<vm>:8080/docs. The admin key is in: docker compose -f /opt/riot-proxy/compose.yaml logs
EOF
